services:
  - type: web
    name: scheduler
    env: python
    plan: free
    buildCommand: |
      python app/seed_employees
      python app/seed_locations
      python app/seed_employee_settings
    startCommand: python main.py
    rootDir: .

